### ISSUE TITLE
Client silently ignores PEM file if user expansion is needed

### ISSUE THREAD

**Issue by MrCreosote** [NERSC/sfapi_client#85]
https://github.com/NERSC/sfapi_client/blob/467c2cc267a7f49e61735876e05055cc8a733e31/src/sfapi_client/_async/client.py#L314-L317

If `name` is something like `~/NERSC/key.pem` then `Path.exists()` will return `False`, even though the file does exist at that location, and the client will remain unauthenticated, which is very confusing.

There's at least two options that could be reasonable:

1. Add `Path.expanduser()` after each Path constructor call
2. Throw an error if `expanduser()` results in a different path if you want to force the user to provide an absolute path or path relative to the working dir

**Comment by cjh1** [comment]
@MrCreosote Thanks for report. I think your first suggest is probably the way to go. @tylern4 would you be able to take a look at fixed this up, as I am currently out of action.

**Comment by MrCreosote** [comment]
If it's just a matter of adding the `expanduser` calls and manually testing I can PR it if you want. I hesitated before because

* I hadn't looked at the tests, but it seems like there are no tests for the `key=` case, so it's just a matter of testing manually
* I'm not sure what platforms you're supporting and if `expanduser` would cause problems on Windows.

If adding the calls, testing on linux, and making a PR agrees with you LMK and I'll do it today

**Comment by MrCreosote** [comment]
Looks like the code is duplicated in `_sync/client.py` as well
