### ISSUE TITLE
Add `json=` kwarg to `[Async]Client.post()`

### ISSUE THREAD

**Issue by MrCreosote** [NERSC/sfapi_client#87]
It'd be nice if the `post()` method of the clients was able to take json data as well as form encoded data, as this would allow the client to make calls to the callback endpoints in beta. I'm currently having to import a separate library for that but the client could easily do it. Something like this maybe?

```diff
diff --git a/src/sfapi_client/_async/client.py b/src/sfapi_client/_async/client.py
--- src/sfapi_client/_async/client.py
+++ src/sfapi_client/_async/client.py
@@ -381,14 +381,18 @@
         | retry_if_http_status_error(),
         wait=tenacity.wait_exponential(max=MAX_RETRY),
         stop=tenacity.stop_after_attempt(MAX_RETRY),
     )
-    async def post(self, url: str, data: Dict[str, Any]) -> httpx.Response:
+    async def post(self, url: str, data: Dict[str, Any] = None, json: Dict[str, Any] = None
+    ) -> httpx.Response:
+        if bool(json) ^ bool(data):  # xor
+            raise ValueError("Exactly one of data or json must be provided")
         client = await self._http_client()
 
         r = await client.post(
             f"{self._api_base_url}/{url}",
             data=data,
+            json=json,
         )
         r.raise_for_status()
 
         return r
```

**Comment by cjh1** [comment]
@MrCreosote While the client is not designed to the a fully fledged http client I don't see a problem with doing this. I would probably just keep the behavior that `httpx` provides, which is `data` has precedence if both are provided. If you would like to put a PR together we would be happy to accept it or I can put something up?

**Comment by MrCreosote** [comment]
I'm happy to do it but I'm having trouble getting the tests to run as it appears there's many missing dependencies in `requirements-dev.txt`. I don't see any specific testing documentation in the repo so what I've been doing is

```
~/github/NERSC/sfapi_client$ pipenv --python 3.11
~/github/NERSC/sfapi_client$ pipenv shell
~/github/NERSC/sfapi_client$ pipenv install -r requirements-dev.txt 
~/github/NERSC/sfapi_client$ PYTHONPATH=src pytest tests
```

So far I've added
```
cryptography
authlib
tenacity
```
to the requirements but at this point it probably makes more sense to ask if I'm doing something wrong.

Regarding tests - the tests for the clients are pretty minimal; based on what's there I wouldn't add any additional tests for these changes to the sync and async clients; I'd just test them against the callback endpoints manually. Is that what you'd expect for a PR?

**Comment by cjh1** [comment]
The `post` method in the client is used by a lot of the other client methods, which have decent test coverage, so manual testing for this change would be fine.

**Comment by MrCreosote** [comment]
Am I doing anything wrong re the missing dependencies or should I just keep going and add them in as I find them?

**Comment by cjh1** [comment]
> Am I doing anything wrong re the missing dependencies or should I just keep going and add them in as I find them?

I am guessing that when we run the test we have the package installed, so many of the deps are installed by that. So if you don't mind adding them that would be great.

**Comment by MrCreosote** [comment]
It appears I need a dev client ID / secret to run the tests [1] - is that something I can get? I don't see a way to specify a dev client in IRIS.

There's a lot of setup required for these tests...

1. https://github.com/NERSC/sfapi_client/blob/main/tests/conftest.py#L24-L34

**Comment by cjh1** [comment]
I am afraid the dev instance is only available to staff ( this is a recent thing ). If you push something I would be happy to test it ( I will be at a conference next week, so my response may be a little delayed ).

**Comment by MrCreosote** [comment]
Ok, I'll make 2 PRs in that case, #1 to add the dependencies, #2 to add the json kwarg. I'll just test via a `/utilities/command` post and a `/callback` post.

**Comment by cjh1** [comment]
> Ok, I'll make 2 PRs in that case, #1 to add the dependencies, #2 to add the json kwarg. I'll just test via a `/utilities/command` post and a `/callback` post.

Sounds good
